config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :reviews, only: [:create, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  root 'home#index'

  resources :books, only: [:index, :show]
  resources :orders, only: [:show, :index]

  as :user do
    get 'login', to: 'users/sessions#new'
    post 'users/sign_in', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

    get 'sign_up', to: 'users/registrations#new'
    post 'users/sign_up', to: 'users/registrations#create'
    post 'sign_up', to: 'users/registrations#create'

    get 'users/edit', to: 'users/registrations#edit'
    put 'users', to: 'users/registrations#update'
    delete 'users', to: 'users/registrations#destroy'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  get 'catalog', to: 'books#index'

  get 'cart', to: 'carts#show'
  post 'cart', to: 'carts#update'

  get 'checkout', to: 'checkout#new'
  post 'checkout', to: 'checkout#create'
  post 'checkouts', to: 'checkout#create'
  get 'checkout/login', to: 'checkout_registration#login'
  post 'checkout/sign_up', to: 'checkout_registration#sign_up'

  get 'settings', to: 'settings#edit'
  post 'settings', to: 'settings#update'
  delete 'settings', to: 'settings#destroy'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @books = Book.order(created_at: :desc).limit(3)
    @first_book = @books.first
    @books = @books.reject { |book| book == @first_book }
    @bestsellers = Book.bestsellers
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def book_first_sentence(book)
    book.description[/^(.*?)[.?!]/]
  end
end

app/views/home/_active_latest_book.html.haml
.item.active
  .row
    .col-sm-5
      .general-img-wrap
        %img.img-shadow.general-thumbnail-img{src: @first_book.cover_url, alt: 'Some amazing book'}
    .col-sm-7
      .mb-60
        %h1= @first_book.title
        %p.lead= book_first_sentence(@first_book)
        %p.lead.small= book_authors(@first_book)
        .general-align
          = button_to 'Buy Now', order_items_path(book_id: @first_book), class: 'btn btn-primary', remote: true

app/views/home/_bestsellers.html.haml
.row
  - @bestsellers.each do |bestseller|
    .col-sm-6.col-md-3
      .general-thumb-wrap
        .thumbnail.general-thumbnail
          %img.img-shadow.general-thumbnail-img{src: bestseller.cover_url, alt: 'Some Cool Book'}
          .thumb-hover
            .general-thumb-link-wrap
              = link_to bestseller, class: 'thumb-hover-link' do
                %i.fa.fa-eye.thumb-icon{'aria-hidden': 'true'}
              = link_to order_items_path(book_id: bestseller), method: :post, class: 'thumb-hover-link', remote: true do
                %i.fa.fa-shopping-cart.thumb-icon
      .mb-35
        .clearfix
          %p.pull-right.font-16.in-gold-500= number_to_euro(bestseller.price)
          %p.title.mr-55= bestseller.title
        %span.divider-sm
        %p.lead.small= book_authors(bestseller)

app/views/home/_inactive_latest_books.html.haml
- @books.each do |book|
  .item
    .row
      .col-sm-5
        .general-img-wrap
          %img.img-shadow.general-thumbnail-img{src: book.cover_url, alt: 'Some amazing book'}
      .col-sm-7
        .mb-60
          %h1= book.title
          %p.lead= book_first_sentence(book)
          %p.lead.small= book_authors(book)
          .general-align
            = button_to 'Buy Now', order_items_path(book_id: book), class: 'btn btn-primary', remote: true

app/views/home/index.html.haml
%main.container
  #slider.carousel.slide{'data-ride': 'carousel'}
    %ol.carousel-indicators
      %li.active{'data-target': '#slider', 'data-slide-to': '0'}
      %li{'data-target': '#slider', 'data-slide-to': '1'}
      %li{'data-target': '#slider', 'data-slide-to': '2'}
    .carousel-inner{role: 'listbox'}
      = render 'active_latest_book'
      = render 'inactive_latest_books'
    %a.left.carousel-control{href: '#slider', role: 'button', 'data-slide': 'prev'}
      %span.icon-prev{'aria-hidden': 'true'}
      %span.sr-only Previous
    %a.right.carousel-control{href: '#slider', role: 'button', 'data-slide': 'next'}
      %span.icon-next{'aria-hidden': 'true'}
      %span.sr-only Next
.container
  .jumbotron.text-center.mb-0
    %h2.h1 Welcome to our amazing Bookstore!
    .mb-res-50
      %p We pore through hundreds of new books each month and select the five best we can find to share with our members.
    = link_to 'Get Started', catalog_path, class: 'btn btn-default'
  .mb-35
    %h3 Best Sellers
    = render 'bestsellers'