config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :reviews, only: [:create, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  root 'home#index'

  resources :books, only: [:index, :show]
  resources :orders, only: [:show, :index]

  as :user do
    get 'login', to: 'users/sessions#new'
    post 'users/sign_in', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

    get 'sign_up', to: 'users/registrations#new'
    post 'users/sign_up', to: 'users/registrations#create'
    post 'sign_up', to: 'users/registrations#create'

    get 'users/edit', to: 'users/registrations#edit'
    put 'users', to: 'users/registrations#update'
    delete 'users', to: 'users/registrations#destroy'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  get 'catalog', to: 'books#index'

  get 'cart', to: 'carts#show'
  post 'cart', to: 'carts#update'

  get 'checkout', to: 'checkout#new'
  post 'checkout', to: 'checkout#create'
  post 'checkouts', to: 'checkout#create'
  get 'checkout/login', to: 'checkout_registration#login'
  post 'checkout/sign_up', to: 'checkout_registration#sign_up'

  get 'settings', to: 'settings#edit'
  post 'settings', to: 'settings#update'
  delete 'settings', to: 'settings#destroy'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :order_items, dependent: :destroy

  def add_book(book_id, quantity = 1)
    current_item = order_items.find_by(book_id: book_id)
    if current_item
      current_item.quantity += quantity.to_i
    else
      current_item = order_items.build(book_id: book_id, quantity: quantity)
    end
    current_item
  end

  def total_price
    order_items.to_a.sum(&:subtotal_price)
  end

  def order_total
    total_price - get_discount
  end

  def cart_size
    order_items.count
  end

  def get_discount
    discount ? discount : 0
  end

  def empty?
    cart_size.zero?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  authorize_resource

  # GET /cart
  def show
  end

  # POST /cart
  def update
    set_coupon_to_params

    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to cart_path, notice: 'Book was successfully updated.' }
      else
        format.html { redirect_to cart_path, notice: '' }
      end
    end
  end

  private

  def set_coupon_to_params
    coupon = Coupon.find_by(code: params[:cart][:discount])
    if coupon&.active
      params[:cart][:discount] = coupon.discount
      coupon.active = false
      coupon.save
    else
      params[:cart][:discount] = nil
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.fetch(:cart, {}).permit(:discount)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def cart_discount(cart)
    discount = cart.discount
    discount ? number_to_euro(discount) : number_to_euro(0)
  end
end

app/views/carts/_cart.html.haml
.visible-xs
  = render 'visible_xs_order_items'
.hidden-xs
  = render 'hidden_xs_order_items'
.general-order-wrap
  .row
    = render 'coupon'
    = render 'summary'

app/views/carts/_coupon.html.haml
= form_for(@cart, url: cart_path, method: :post) do |f|
  .col-sm-4
    .input-group.general-input-group
      = f.label :discount, 'Enter Your Coupon Code', class: 'input-label'
      = f.text_field :discount, value: '', placeholder: 'Enter Your Coupon Code ', class: 'form-control mb-30'
      %div
        = f.submit('Apply Coupon', class: 'btn btn-primary mr-5 mb-15 visible-xs-inline-block')
        = f.submit('Apply Coupon', class: 'btn btn-primary mb-15 res-block')

app/views/carts/_empty_cart.html.haml
.text-center.mb-80
  %h2 Your cart is empty
.text-center
  = link_to 'Go to Catalog', catalog_path, class: 'btn btn-default mb-20'

app/views/carts/_hidden_xs_order_items.html.haml
%table.table.table-hover
  %tr.no-hover
    %th.col-pic.pl-0
      %span.in-grey-600 Product
    %th.col-title
    %th.col-price
      %span.in-grey-600 Price
    %th.col-quantity
      %span.in-grey-600 Quantity
    %th.col-total
      %span.in-grey-600 SubTotal
    %th.col-close

  - @cart.order_items.order(:id).each do |order_item|
    %tr
      %td
        .general-img-wrap-table
          = link_to order_item.book do
            %img.cart-img-shadow.pull-left{src: order_item.book.cover_url, alt: 'Some cool book'}
      %td
        = link_to(order_item.book.title, order_item.book, class: 'title')
      %td
        %span.font-16.in-gold-500= number_to_euro(order_item.book.price)
      %td
        = form_for order_item, method: :put, remote: true do |f|
          .input-group
            = link_to '', order_item_path(order_item, order_item: { quantity: :dec }), method: :put, remote: true, class: 'input-link fa fa-minus line-height-40'
            = f.number_field :quantity, class: 'form-control quantity-input', id: 'quantity', value: order_item.quantity, min: 1
            = link_to '', order_item_path(order_item, order_item: { quantity: :inc }), method: :put, remote: true, class: 'input-link fa fa-plus line-height-40'
      %td
        %span.font-16.in-gold-500= number_to_euro(order_item.subtotal_price)
      %td
        = link_to order_item, method: :delete, class: 'close general-cart-close' do
          %span{'aria-hidden': 'true'} &times;

app/views/carts/_summary.html.haml
#cart_summary
  .col-sm-8
    .res-mr-200.text-center.general-text-right
      %p.in-gold-500.font-18 Order Summary
      %table.general-summary-table.general-summary-table-right.general-text-right
        %tr
          %td
            %p.font-16 Subtotal:
          %td
            %p.font-16= number_to_euro(@cart.total_price)
        %tr
          %td
            %p.font-16 Coupon:
          %td
            %p.font-16= cart_discount(@cart)
        %tr
          %td
            %strong.font-18 Order Total:
          %td
            %strong.font-18= number_to_euro(@cart.order_total)
      = link_to 'Checkout', checkout_path, class: 'btn btn-default mb-20 visible-xs-inline-block'
  .text-center
    = link_to 'Checkout', checkout_path, class: 'btn btn-default mb-20 hidden-xs'

app/views/carts/_visible_xs_order_items.html.haml
- @cart.order_items.each do |order_item|
  .general-cart-item.divider-lg-bottom
    = button_to order_item, method: :delete, class: 'close general-cart-close' do
      %span{'aria-hidden': 'true'} &times;
    .general-img-wrap-table
      = link_to order_item.book do
        %img.cart-img-shadow{src: order_item.book.cover_url, alt: 'Some cool book'}
    = link_to(order_item.book.title, order_item.book, class: 'title')
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500= number_to_euro(order_item.book.price)
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          .input-group
            %a.input-link{href: '#'}
              %i.fa.fa-minus.line-height-40
            %input.form-control.quantity-input{type: 'number', value: order_item.quantity, min: 1}
            %a.input-link{href: '#'}
              %i.fa.fa-plus.line-height-40
      %tr
        %td
          %span.in-grey-600 SubTotal
        %td
          %span.font-16.in-gold-500= number_to_euro(order_item.subtotal_price)

app/views/carts/show.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Cart
  - if @cart.empty?
    = render 'empty_cart'
  -else
    = render 'cart'