config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :reviews, only: [:create, :destroy]
  resources :order_items, only: [:create, :update, :destroy]

  root 'home#index'

  resources :books, only: [:index, :show]
  resources :orders, only: [:show, :index]

  as :user do
    get 'login', to: 'users/sessions#new'
    post 'users/sign_in', to: 'users/sessions#create'
    delete 'logout', to: 'users/sessions#destroy'

    get 'sign_up', to: 'users/registrations#new'
    post 'users/sign_up', to: 'users/registrations#create'
    post 'sign_up', to: 'users/registrations#create'

    get 'users/edit', to: 'users/registrations#edit'
    put 'users', to: 'users/registrations#update'
    delete 'users', to: 'users/registrations#destroy'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  get 'catalog', to: 'books#index'

  get 'cart', to: 'carts#show'
  post 'cart', to: 'carts#update'

  get 'checkout', to: 'checkout#new'
  post 'checkout', to: 'checkout#create'
  post 'checkouts', to: 'checkout#create'
  get 'checkout/login', to: 'checkout_registration#login'
  post 'checkout/sign_up', to: 'checkout_registration#sign_up'

  get 'settings', to: 'settings#edit'
  post 'settings', to: 'settings#update'
  delete 'settings', to: 'settings#destroy'
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/admins/shared/_login_form.html.haml
= form_for(resource, html: {class: 'general-form'}, as: resource_name, url: session_path(resource_name)) do |f|
  -#.form-group.mb-30
  -#  .color-red.text-center= flash[:alert]
  -#  = f.label :email, class: 'control-label input-label'
  -#  - if resource.errors[:email].empty?
  -#    = f.email_field :email, autofocus: true, id: 'email', class: 'form-control', placeholder: 'Enter Email'
  -#  - else
  -#    = f.email_field :email, autofocus: true, id: 'email', class: 'form-control borders-red', placeholder: 'Enter Email'
  -#    = errors_for(:email)

  .form-group.mb-30
    .color-red.text-center= flash[:alert]
    = f.label :email, class: 'control-label input-label'
    - if resource.errors[:email].empty?
      = f.email_field :email, autofocus: true, id: 'email', class: 'form-control', placeholder: 'Enter Email'
    - else
      = f.email_field :email, autofocus: true, id: 'email', class: 'form-control borders-red', placeholder: 'Enter Email'
      = errors_for(:email)

  .form-group.mb-30
    = f.label :password, class: 'control-label input-label'
    - if resource.errors[:password].empty?
      = f.password_field :password, autocomplete: 'off', id: 'password', class: 'form-control', placeholder: 'Password'
    - else
      = f.password_field :password, autocomplete: 'off', id: 'password', class: 'form-control borders-red', placeholder: 'Password'
      = errors_for(:password)

  - if devise_mapping.rememberable?
    .form-group.checkbox.text-center.mb-30
      %label.checkbox-label
        = f.check_box :remember_me, class: 'checkbox-input', hidden: 'true'
        %span.checkbox-icon
          %i.fa.fa-check
        %span.checkbox-text Remember me

  .text-center
    = f.submit 'Log in', class: 'btn btn-default mb-20'